# Generated by Django 3.1.3 on 2020-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason_approved',
            name='display_name',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='reason_unapproved',
            name='display_name',
            field=models.TextField(max_length=11),
        ),
    ]
